name: Run bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bot Tournament branch
        uses: actions/checkout@v4
        with:
          repository: TheXdOneHimSelf/bot
          ref: Tournament

      - name: Cache pip downloads
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Download latest Stockfish dev
        run: |
          mkdir -p engines
          curl -L -o stockfish.zip http://abrok.eu/stockfish/latest/linux/stockfish_x64_modern.zip
          unzip -o stockfish.zip -d engines/
          mv engines/stockfish_* engines/stockfish

      - name: Overwrite config.yml with main branch version
        run: |
         curl -L -o config.yml https://raw.githubusercontent.com/GoogleChess/TestBot/main/config.yml

      - name: Download and rename files
        run: |
          mkdir -p engines
          curl -L -o engines/draw.bin https://raw.githubusercontent.com/TheXdOneHimSelf/Polygot/main/draw.bin
          curl -L -o engines/white.bin https://raw.githubusercontent.com/TheXdOneHimSelf/Polygot/main/white.bin
          curl -L -o engines/black.bin https://raw.githubusercontent.com/TheXdOneHimSelf/Polygot/main/black.bin

      - name: Install dependencies & prepare
        run: |
          pip install --no-cache-dir --prefer-binary -r requirements.txt
          sed -i "s/XXXXXXXXXXXXXXXXXXX/${{ secrets.TOKEN }}/g" config.yml
          chmod +x ./engines/stockfish

      - name: Run Bot
        run: |
          echo "Starting bot..."
          python3 -u user_interface.py &
          PID=$!
          ( sleep 20700 && echo "Time up. Killing bot..." && kill -SIGTERM $PID ) &
          wait $PID
          echo "Bot ended cleanly."
          
      - name: Trigger workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'run.yml',
              ref: 'main'
            })
